on:
  pull_request:
  push:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Start server in background
        run: npm run dev &

      - name: Wait for server to be ready
        uses: jakejarvis/wait-action@v0.1.1
        with:
          url: http://localhost:3001
          timeout: 60

      - name: Run Cypress tests
        run: npm run test  # Or your specific Cypress command
